name: Flujo de trabajo con fichero de texto

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Establecer variable de salida en PowerShell
      id: paso1
      run: |
        $variable = "Hola desde PowerShell"
        Write-Host "La variable es $variable"
        echo $variable > variable.txt

    - name: Guardar variable como artefacto
      uses: actions/upload-artifact@v2
      with:
        name: variables
        path: variable.txt

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - name: Descargar artefactos
      uses: actions/download-artifact@v2
      with:
        name: variables

    - name: Leer variable desde archivo
      run: |
        $variable = Get-Content variable.txt
        Write-Host "La variable de salida es $variable"
